using System;
using System.IO;
using System.Text;

namespace CommandFramework.UI.Compiler
{
    /// <summary>
    /// Build-time compiler that discovers .ui.html and .ui.css templates and generates optimized C# code.
    /// </summary>
    public static class UICompiler
    {
        public static string CompileToCSharpClass(string className, string htmlContent, string cssContent)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This code was generated by Command Framework UI Compiler.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using CommandFramework.UI.Declarative;");
            sb.AppendLine();
            sb.AppendLine("namespace CommandFramework.UI.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            // Embed raw strings
            string escapedHtml = htmlContent.Replace("\"", "\"\"");
            string escapedCss = (cssContent ?? string.Empty).Replace("\"", "\"\"");

            sb.AppendLine($"        public const string HtmlSource = @\"{escapedHtml}\";");
            sb.AppendLine($"        public const string CssSource = @\"{escapedCss}\";");
            sb.AppendLine();
            sb.AppendLine("        private static UIDocument _cachedDoc;");
            sb.AppendLine();
            sb.AppendLine("        public static UIDocument GetDocument()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_cachedDoc == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                _cachedDoc = UIDocument.Parse(HtmlSource, CssSource);");
            sb.AppendLine("            }");
            sb.AppendLine("            return _cachedDoc;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        public static void ProcessDirectory(string searchDirectory, string outputDirectory)
        {
            if (!Directory.Exists(searchDirectory)) return;
            if (!Directory.Exists(outputDirectory)) Directory.CreateDirectory(outputDirectory);

            var htmlFiles = Directory.GetFiles(searchDirectory, "*.ui.html", SearchOption.AllDirectories);
            foreach (var htmlPath in htmlFiles)
            {
                string baseName = Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(htmlPath));
                string cssPath = Path.ChangeExtension(htmlPath, ".ui.css");

                string html = File.ReadAllText(htmlPath);
                string css = File.Exists(cssPath) ? File.ReadAllText(cssPath) : null;

                string className = "UI_" + ToPascalCase(baseName);
                string csharpCode = CompileToCSharpClass(className, html, css);

                string outPath = Path.Combine(outputDirectory, $"{className}.g.cs");
                File.WriteAllText(outPath, csharpCode, Encoding.UTF8);
            }
        }

        private static string ToPascalCase(string text)
        {
            if (string.IsNullOrEmpty(text)) return "Template";
            var parts = text.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var p in parts)
            {
                if (p.Length > 0)
                {
                    sb.Append(char.ToUpperInvariant(p[0]));
                    if (p.Length > 1) sb.Append(p.Substring(1).ToLowerInvariant());
                }
            }
            return sb.ToString();
        }
    }
}
